services:
  mongodb:
    image: mongo:8
    container_name: air-quality-mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db
      - ./scripts/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js:ro

    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 3s
      retries: 5


  pipeline:
    build: .
    container_name: air-quality-pipeline

    depends_on:
      mongodb:
        condition: service_healthy

    environment:
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DATABASE: air_quality_db
      DATA_FILE: data/sample_city_hour.csv

    volumes:
      - ./logs:/app/logs


volumes:
  mongodb_data: